export const repository = 'https://github.com/mechiland/aven';
export const release = `${repository}/releases/tag/v0.1.0-prototype`;
export const docs = `${repository}/blob/v0.1.0-prototype/docs`;

export const scenes = [
  { id: 'files', aven: 'evidence/verification/iso-candidate5/files-sc-grid.png', stock: 'evidence/stock/round-00/files-mixed-clean-1x.png', app: 'Dolphin' },
  { id: 'preview', aven: 'evidence/verification/iso-candidate5/preview-earthrise.png', stock: 'evidence/stock/round-00/preview-image-1x.png', app: 'Aven Preview' },
  { id: 'browser', aven: 'evidence/verification/iso-candidate5/browser-sc.png', stock: 'evidence/stock/round-00/browser-sc-1x.png', app: 'Firefox' },
  { id: 'mail', aven: 'evidence/verification/iso-candidate5/mail-sc.png', stock: 'evidence/stock/round-00/mail-sc-1x.png', app: 'Thunderbird' },
  { id: 'photos', aven: 'evidence/verification/iso-candidate5/photos-grid.png', stock: 'evidence/stock/round-00/photos-grid-1x.png', app: 'Gwenview' },
];

export const locales = {
  'zh-cn': {
    lang: 'zh-CN', title: 'Aven — 日常，自有从容。', description: 'Aven，基于 Fedora Kinoite 的桌面原型。用心打磨文件、快速预览、浏览器、邮件、照片与中英文排版，让日常自有从容。查看真实截图与原生 Fedora 对比。',
    skip: '跳转到内容', navLabel: '主导航', nav: ['日常体验', '前后对比', '文字之美'], get: '体验 Aven', switch: 'English', switchLang: 'en', menu: '展开导航', closeMenu: '收起导航',
    eyebrow: '认识 Aven', hero: '日常，<br><span>自有从容。</span>', intro: '一个更从容的 Linux 桌面。<br>从每一份文件，到每一次阅读。', explore: '看看不一样', version: '0.1.0 原型现已开放体验',
    heroCaption: 'Aven 0.1.0 · 实际安装后的桌面', heroAlt: 'Aven 实际桌面：玉绿色壁纸、文件网格与简洁的底部面板',
    dailyEyebrow: '熟悉的日常，细致的新意', dailyTitle: '小事之间，<br>处处用心。', dailyIntro: '整理文件，读一封邮件，重温一张照片。<br>Aven 把心思放在每天与你相伴的细节里。',
    tabsLabel: '选择应用体验', screenshot: '查看完整截图', sceneTitle: ['找得到，也看得清。', '先看一眼，再进一步。', '把注意力，交给内容。', '每一句话，都值得好好读。', '让回忆，一眼可见。'],
    sceneText: ['常用位置清楚排列，缩略图更大，中英文文件名自然相处。熟悉的 Dolphin，让整理更有条理。', '选中文件，按下 Ctrl + Alt + P。照片、PDF、文字和常见媒体，直接预览；按 Esc 回到文件，按 Enter 在默认应用中打开。', '熟悉的 Firefox，融入统一的窗口与字体。浏览、下载、选择文件，在同一个桌面节奏里自然衔接。', '在 Thunderbird 中读信、写信。更舒展的正文间距，让中文段落与英文句子都拥有合适的留白。', '在 Gwenview 中浏览相册，让大幅缩略图带你找回那一天。打开照片，还能切换与全屏查看。'],
    labels: ['文件', '快速预览', '浏览器', '邮件', '照片'], shortcut: '选中文件 · Ctrl + Alt + P · Esc 返回', imageNote: '真实界面截图 · 示例文件与虚构邮件用于演示',
    compareEyebrow: '改变，看得见', compareTitle: '同样的日常。<br>不同的感受。', compareIntro: '拖动分界线，看看原生 Fedora Kinoite 与 Aven 的区别。', compareLabel: '截图前后对比', slider: '调整原生 Fedora 与 Aven 截图的分界位置', drag: '左右拖动对比', before: '原生 Fedora', after: 'Aven', original: '打开原图', compareNote: '两侧均为 1920 × 1200、100% 缩放的原生截图。Aven 来自 0.1.0 安装版本；Fedora 为原生基准，使用相同演示内容。窗口布局与部分操作状态存在差异。', compareDetails: ['更大的文件缩略图，更从容的排列。', '从信息栏小图，到独立的大幅预览。', '统一的是浏览器界面；网页内容保持原样。', '更舒展的正文行距，更清晰的阅读区域。', '同一组照片，以更大的缩略图呈现。'],
    typeEyebrow: '文字之美', typeTitle: '中文，英文。<br><span>都读得入心。</span>', typeIntro: '以 Noto 字体家族为基础，认真对待字重、行距与中英混排。从文件名到长段落，让每一次阅读自然、清晰。', typeSample: '字里行间，<br>留一点从容。', typeEnglish: 'A little room to read.', typeMeta: '中文 · English · 123', typeLink: '查看真实中文界面', typeCaption: 'Aven 文字预览 · 简体中文与 Latin',
    foundationEyebrow: '从容，也有底气', foundationTitle: '熟悉的应用。<br>扎实的基础。', foundationIntro: 'Aven 基于 Fedora Kinoite，聚焦日常体验。<br>你熟悉的 Linux 底层能力，依然在这里。', foundation: [
      ['Fedora Atomic', '稳稳向前。', '保留 Fedora 的原子部署、更新来源与系统回滚入口。'],
      ['KDE Plasma', '熟悉，更合拍。', 'Dolphin、Firefox、Thunderbird 和 Gwenview，在统一的视觉细节中各展所长。'],
      ['开放开发', '每一步，都可了解。', '源代码、原生截图、安装说明与验证记录，都在公开仓库中。'],
    ], source: '查看源代码',
    downloadEyebrow: 'AVEN 0.1.0 · PROTOTYPE', downloadTitle: '给日常，<br>一点新感受。', downloadIntro: '从一个全新的桌面开始。', download: '获取原型', guide: '阅读安装指南', platform: 'x86_64 · Fedora Kinoite 44 · 离线安装 ISO', prerelease: '当前为评估用预发布版本，建议先在虚拟机中体验。', installTitle: '如何开始体验？', installSteps: ['在 GitHub Release 下载 4 个 ISO 分卷、ISO-PARTS.json 和 reassemble-iso.py，放在同一文件夹。', '运行 python3 reassemble-iso.py（Windows 使用 py -3 reassemble-iso.py），校验并合成为完整 ISO。', '将 ISO 挂载到虚拟机，或写入至少 16 GB 的 USB 设备，再按照安装指南完成安装。'], installNote: '这是安装镜像，不是 Live 桌面；单个分卷无法启动。合并文件时请使用支持硬链接的文件系统。',
    evidenceTitle: '关于截图与版本', evidenceText: '本页 Aven 截图均来自 0.1.0 原型 ISO 的实际安装环境，保持原始像素，未经修饰。相册、网页与邮件为验证用示例内容，不会预填到你的个人账户中。', limits: '当前版本已验证虚拟机安装与日常基础操作；实机硬件、Secure Boot 与实际系统回滚尚未验证。初次文件列表的行高、照片胶片栏大小仍有待打磨。', evidence: '安装验证记录', critic: '界面评审记录', credits: '图像来源与许可', copyright: 'Aven 项目', footerLine: '从日常出发。', footerSource: '源代码', releaseNotes: '发布说明', languageLabel: '网站语言', dialogClose: '关闭截图', zoomHint: '完整原始截图，可打开原图查看文字细节。',
  },
  en: {
    lang: 'en', title: 'Aven — A little more calm.', description: 'Meet Aven, a focused Fedora Kinoite desktop prototype. Thoughtful files, previews, browsing, mail, photos and Chinese/Latin typography. Explore real screenshots and compare with stock Fedora.',
    skip: 'Skip to content', navLabel: 'Main navigation', nav: ['Everyday', 'Compare', 'Typography'], get: 'Try Aven', switch: '简体中文', switchLang: 'zh-cn', menu: 'Open navigation', closeMenu: 'Close navigation',
    eyebrow: 'Meet Aven', hero: 'A little more<br><span>calm.</span>', intro: 'A more considered Linux desktop.<br>For the things you do every day.', explore: 'See the difference', version: 'The 0.1.0 prototype is here',
    heroCaption: 'Aven 0.1.0 · Captured from an installed desktop', heroAlt: 'The real Aven desktop with jade wallpaper, a spacious file grid and a compact bottom panel',
    dailyEyebrow: 'The everyday, thoughtfully refined', dailyTitle: 'Little things.<br>Considered.', dailyIntro: 'Find a file. Read a message. Revisit a memory.<br>Aven brings care to the details you live with.',
    tabsLabel: 'Choose an application', screenshot: 'View full screenshot', sceneTitle: ['A place for everything.', 'A closer look. A keystroke away.', 'More room for what matters.', 'Give every word some room.', 'Memories, at a glance.'],
    sceneText: ['Clear places, larger thumbnails and comfortable Chinese and Latin filenames. The familiar Dolphin file manager, with a more considered view.', 'Select a file and press Ctrl + Alt + P. Preview images, PDFs, text and common media. Esc returns to Files; Enter opens the default application.', 'The Firefox you know, with a consistent frame and typography. Browsing, downloads and native file selection feel at home on the same desktop.', 'Read and write in Thunderbird. More generous text spacing gives Chinese paragraphs and English sentences room to breathe.', 'Explore your albums in Gwenview, with larger thumbnails that bring the day back into view. Open a photo, move through the album or go full screen.'],
    labels: ['Files', 'Preview', 'Browser', 'Mail', 'Photos'], shortcut: 'Select a file · Ctrl + Alt + P · Esc to return', imageNote: 'Real desktop captures · Sample files and fictional mail',
    compareEyebrow: 'The difference is in the details', compareTitle: 'Same everyday.<br>A different feel.', compareIntro: 'Move the divider to compare stock Fedora Kinoite with Aven.', compareLabel: 'Before and after screenshots', slider: 'Adjust the divider between stock Fedora and Aven screenshots', drag: 'Drag to compare', before: 'Stock Fedora', after: 'Aven', original: 'Open original', compareNote: 'Native captures at 1920 × 1200 and 100% scale. Aven is the installed 0.1.0 prototype; the baseline is stock Fedora, using the same sample content. Window layouts and some interaction states differ.', compareDetails: ['Larger file thumbnails, with a more spacious arrangement.', 'From a small information-panel image to a dedicated preview.', 'A consistent browser frame; the webpage itself is unchanged.', 'More generous line spacing and a clearer reading area.', 'The same album, with larger photo thumbnails.'],
    typeEyebrow: 'Thoughtful typography', typeTitle: 'Every character.<br><span>At home.</span>', typeIntro: 'Built on the Noto font family, with care for weight, spacing and mixed Chinese and Latin text. From filenames to full paragraphs, reading feels clear and natural.', typeSample: '字里行间，<br>留一点从容。', typeEnglish: 'A little room to read.', typeMeta: '中文 · English · 123', typeLink: 'See real Chinese typography', typeCaption: 'Aven text preview · Simplified Chinese and Latin',
    foundationEyebrow: 'Calm on the surface. Capable underneath.', foundationTitle: 'Familiar apps.<br>Solid foundations.', foundationIntro: 'Built on Fedora Kinoite. Focused on the everyday.<br>The Linux foundations you know are still here.', foundation: [
      ['Fedora Atomic', 'Built to move forward.', 'Retains Fedora’s Atomic deployments, update origin and system rollback entry.'],
      ['KDE Plasma', 'Familiar feels right.', 'Dolphin, Firefox, Thunderbird and Gwenview, brought together by considered visual details.'],
      ['Open development', 'See how it comes together.', 'Explore the source, native screenshots, installation guide and verification records in the public repository.'],
    ], source: 'Explore the source',
    downloadEyebrow: 'AVEN 0.1.0 · PROTOTYPE', downloadTitle: 'Make a little<br>room for Aven.', downloadIntro: 'A fresh perspective on your everyday desktop.', download: 'Get the prototype', guide: 'Read the install guide', platform: 'x86_64 · Fedora Kinoite 44 · Offline installer ISO', prerelease: 'An evaluation prerelease. Start in a virtual machine.', installTitle: 'How do I get started?', installSteps: ['Download all 4 ISO parts, ISO-PARTS.json and reassemble-iso.py from the GitHub release into one folder.', 'Run python3 reassemble-iso.py (py -3 reassemble-iso.py on Windows) to verify the parts and assemble the complete ISO.', 'Attach the ISO to a virtual machine, or write it to a USB drive of at least 16 GB. Follow the installation guide.'], installNote: 'This is an installer, not a live desktop. Individual parts cannot boot. Reconstruction requires a filesystem with hard-link support.',
    evidenceTitle: 'About the screenshots and release', evidenceText: 'All Aven screenshots on this page were captured from the installed 0.1.0 prototype ISO. Original pixels are preserved without retouching. Albums, webpages and messages are verification fixtures, not content prefilled into your personal accounts.', limits: 'Virtual-machine installation and basic daily operations have been verified. Physical hardware, Secure Boot and live system rollback remain untested. Initial file-list density and photo filmstrip sizing still need refinement.', evidence: 'Installation verification', critic: 'Visual review', credits: 'Image sources and licenses', copyright: 'The Aven project', footerLine: 'Consider the everyday.', footerSource: 'Source code', releaseNotes: 'Release notes', languageLabel: 'Website language', dialogClose: 'Close screenshot', zoomHint: 'An unmodified capture. Open the original to inspect text at native resolution.',
  },
};
