export const repository = 'https://github.com/mechiland/aven';
export const release = `${repository}/releases/tag/v0.3.1`;
export const docs = `${repository}/blob/main/docs`;
export const updateRelease = `${repository}/releases/tag/aven-kinoite-44`;
export const assetVersion = 'union-0.4.0-round08';

export const scenes = [
  { id: 'files', aven: 'evidence/aven/round-08/chinese-files-final.png', stock: 'evidence/stock/round-00/files-mixed-clean-1x.png', app: 'Dolphin', round: '08' },
  { id: 'preview', aven: 'evidence/aven/round-06/preview-image-accepted-1x.png', stock: 'evidence/stock/round-00/preview-image-1x.png', app: 'Aven Preview', round: '06' },
  { id: 'browser', aven: 'evidence/aven/round-06/browser-sc-accepted-1x.png', stock: 'evidence/stock/round-00/browser-sc-1x.png', app: 'Firefox', round: '06' },
  { id: 'mail', aven: 'evidence/aven/round-07/mail-final.png', stock: 'evidence/stock/round-00/mail-sc-1x.png', app: 'Thunderbird', round: '07' },
  { id: 'photos', aven: 'evidence/aven/round-07/photos-restored-dot.png', stock: 'evidence/stock/round-00/photos-grid-1x.png', app: 'Gwenview', round: '07' },
];

export const locales = {
  'zh-cn': {
    lang: 'zh-CN', title: 'Aven Union — 日常，自有从容。', description: 'Aven Union，基于 Fedora Kinoite 的桌面原型。清楚的中英文排版、全宽半透明底栏与原生应用。查看真实截图，在现有 Kinoite 44 上在线安装并按组件更新，也可下载离线 ISO。',
    skip: '跳转到内容', navLabel: '主导航', nav: ['日常体验', '前后对比', '文字之美', '安装与更新'], get: '体验 Union', switch: 'English', switchLang: 'en', menu: '展开导航', closeMenu: '收起导航',
    eyebrow: '认识 Aven Union', hero: '日常，<br><span>自有从容。</span>', intro: '清楚的文字，轻盈的窗口。<br>从每一份文件，到每一次阅读。', explore: '看看不一样', version: '在线更新版 0.4.0 · 离线 ISO 0.3.1',
    heroCaption: '最新桌面 · round 08 原始截图 · 全宽底栏与中英文文件名', heroAlt: 'Union 真实桌面：Dolphin 中英文文件列表、圆角窗口和全宽半透明底栏，左侧工作区、居中应用与右侧系统托盘',
    dailyEyebrow: '熟悉的日常，细致的新意', dailyTitle: '小事之间，<br>处处用心。', dailyIntro: '整理文件，读一封邮件，重温一张照片。<br>Union 把心思放在每天与你相伴的细节里。',
    tabsLabel: '选择应用体验', screenshot: '查看完整截图', sceneTitle: ['找得到，也看得清。', '先看一眼，再进一步。', '把注意力，交给内容。', '每一句话，都值得好好读。', '让回忆，一眼可见。'],
    sceneText: ['常用位置、路径与文件列表清楚排列。浅灰侧栏、蓝色选择态与克制的字重，让 Dolphin 的中英文文件名自然相处。', '选中文件，按下 Ctrl + Alt + P。照片、PDF、文字和常见媒体，直接预览；按 Esc 回到文件，按 Enter 在默认应用中打开。', 'Firefox 的地址栏、导航与窗口按钮融入同一行。单页浏览更简洁，打开多个标签页时仍保留完整标签栏。', 'Thunderbird 的文件夹、邮件列表与正文各有位置。标题用 500 字重强调，正文保留常规字重；工具栏采用真实应用命令。', '在 Gwenview 中浏览相册。照片网格、浅灰侧栏和统一窗口轮廓，衔接原生的切换、缩放与全屏查看。'],
    labels: ['文件', '快速预览', '浏览器', '邮件', '照片'], shortcut: '选中文件 · Ctrl + Alt + P · Esc 返回', imageNote: '原始实机截图 · 文件来自 round 08；邮件、照片来自 round 07；浏览器、预览来自 round 06。较早批次保留浮动 Dock。示例邮件为虚构内容。', captureLabel: '截图批次', captureSource: '原始记录',
    compareEyebrow: '改变，看得见', compareTitle: '同样的日常。<br>不同的感受。', compareIntro: '拖动分界线，看看原生 Fedora Kinoite 与 Union 的区别。', compareLabel: '截图前后对比', slider: '调整原生 Fedora 与 Union 截图的分界位置', drag: '左右拖动对比', before: '原生 Fedora', after: 'Union', original: '打开原图', compareNote: '两侧均为 1920 × 1200、100% 缩放的原始截图。Union 来自不同批次的测试虚拟机（round 06 / 07 / 08），与 ISO 新装和在线更新验证分别记录。窗口布局、示例内容与操作状态存在差异；只有本组文件截图显示全宽底栏。', compareDetails: ['中英文文件列表与全宽底栏；Union 截图来自 round 08。', '从信息栏小图，到独立预览窗口；两侧示例图片不同。', '统一的是浏览器界面；网页内容由网站自行决定。', '三栏阅读布局、500 强调字重与 round 07 浮动 Dock。', '同一组照片，统一的侧栏、窗口与 Dock。'],
    typeEyebrow: '文字之美', typeTitle: '中文，英文。<br><span>都读得入心。</span>', typeIntro: '界面以 Adwaita Sans 搭配 Noto 中文字体。常规文字使用 400 字重，主题管理的中文标题与重点使用真实的 500 字重；从文件名到邮件，让层次更清楚，阅读更轻松。', typeSample: '字里行间，<br>留一点从容。', typeEnglish: 'A little room to read.', typeMeta: '网页字样 · 500 Medium', typeFamily: 'Noto Sans CJK', typeLink: '查看真实中文界面', typeCaption: 'Union 文字预览 · 简体中文与 Latin',
    dockEyebrow: '轻盈的桌面', dockTitle: '展开日常，<br>各有位置。', dockText: '全宽半透明底栏贴合屏幕下沿。工作区在左，常用应用居中，系统托盘与日期时间在右。原生应用的启动、切换与运行提示，仍然触手可及。', dockLink: '查看最新底栏原图',
    foundationEyebrow: '从容，也有底气', foundationTitle: '熟悉的应用。<br>扎实的基础。', foundationIntro: 'Union 基于 Fedora Kinoite，聚焦日常体验。<br>你熟悉的 Linux 底层能力，依然在这里。', foundation: [
      ['Fedora Atomic', '稳稳向前。', '保留 Fedora 的原子部署、更新来源与系统回滚入口。'],
      ['KDE Plasma', '熟悉，更合拍。', 'Dolphin、Firefox、Thunderbird 和 Gwenview，在统一的视觉细节中各展所长。'],
      ['开放开发', '每一步，都可了解。', '源代码、原始截图、安装说明与验证记录，都在公开仓库中。'],
    ], source: '查看源代码',
    downloadEyebrow: 'AVEN 0.4.0 · 在线安装与更新', downloadTitle: '给日常，<br>一点新感受。', downloadIntro: '已有 Kinoite，直接安装。<br>下一次改进，按组件更新。', download: '下载 Union 0.3.1 ISO', pendingDownload: 'ISO 发布准备中', pendingNote: '单文件镜像与校验信息将在发布完成后提供。', guide: '阅读安装指南', platform: 'x86_64 · Fedora Kinoite 44 · 离线安装 ISO', prerelease: '基于 Plasma 6.8 Beta 的实验性原型，建议先在虚拟机中体验。', sizeLabel: '文件大小', checksumLabel: 'SHA-256 校验值', manifestLabel: '下载信息 JSON', installTitle: '使用 ISO 安装', installSteps: ['点击下载，保存完整的 Aven Union 0.3.1 ISO 文件，无需合并分卷。', '核对文件大小，并将文件的 SHA-256 与本页校验值比较。', '将 ISO 挂载到虚拟机，或写入至少 16 GB 的 USB 设备，再按照安装指南完成安装。'], installNote: '这是安装镜像，不是 Live 桌面。安装方式与已验证范围请参阅安装指南。',
    evidenceTitle: '关于截图与版本', evidenceText: '本页保留原始截图像素，未经修饰。首页与文件为 round 08 全宽底栏；邮件、照片为 round 07；浏览器、预览与排版为 round 06。在线更新区另附安装后中文截图。各批次截图、ISO 安装与在线更新验证分别记录；相册、网页与邮件为测试内容。', limits: 'Union 的整体、中文视觉评分与三秒差异评审仍待完成。在线安装、组件升级、中断恢复与 Aven 配置回滚已经验证；这不代表 Fedora 系统部署回滚已重新验证。物理硬件与 Secure Boot 的验证范围见 ISO 记录。', evidence: '安装验证记录', critic: '截图与比较记录', credits: '图像来源与许可', copyright: 'Aven 项目', footerLine: '从日常出发。', footerSource: '源代码', releaseNotes: '发布说明', languageLabel: '网站语言', dialogClose: '关闭截图', zoomHint: '完整原始截图，可打开原图查看文字细节。',
  },
  en: {
    lang: 'en', title: 'Aven Union — A little more calm.', description: 'Aven Union, a focused Fedora Kinoite desktop prototype. Clear Chinese and Latin typography, a full-width translucent panel and native apps. Explore real screenshots, install on existing Kinoite 44 and get component updates, or download the offline ISO.',
    skip: 'Skip to content', navLabel: 'Main navigation', nav: ['Everyday', 'Compare', 'Typography', 'Install & update'], get: 'Try Union', switch: '简体中文', switchLang: 'zh-cn', menu: 'Open navigation', closeMenu: 'Close navigation',
    eyebrow: 'Meet Aven Union', hero: 'A little more<br><span>calm.</span>', intro: 'Clearer words. Lighter windows.<br>For the things you do every day.', explore: 'See the difference', version: 'Online release 0.4.0 · Offline ISO 0.3.1',
    heroCaption: 'Latest desktop · Original round 08 capture · Full-width panel and Chinese/Latin filenames', heroAlt: 'The real Union desktop with Chinese and Latin filenames in Dolphin, rounded windows and a full-width translucent panel with workspaces left, apps centered and the tray right',
    dailyEyebrow: 'The everyday, thoughtfully refined', dailyTitle: 'Little things.<br>Considered.', dailyIntro: 'Find a file. Read a message. Revisit a memory.<br>Union brings care to the details you live with.',
    tabsLabel: 'Choose an application', screenshot: 'View full screenshot', sceneTitle: ['A place for everything.', 'A closer look. A keystroke away.', 'More room for what matters.', 'Give every word some room.', 'Memories, at a glance.'],
    sceneText: ['Clear places, paths and file lists. A pale sidebar, blue selection and restrained weights bring Chinese and Latin filenames together in Dolphin.', 'Select a file and press Ctrl + Alt + P. Preview images, PDFs, text and common media. Esc returns to Files; Enter opens the default application.', 'Firefox navigation, address bar and window controls share one row. A single page stays compact; multiple pages retain the full tab strip.', 'Folders, messages and reading each have their place in Thunderbird. Medium-weight headings sit beside regular text, with real application commands in the toolbar.', 'Browse albums in Gwenview. A photo grid, pale sidebar and consistent window frame accompany native navigation, zoom and full-screen viewing.'],
    labels: ['Files', 'Preview', 'Browser', 'Mail', 'Photos'], shortcut: 'Select a file · Ctrl + Alt + P · Esc to return', imageNote: 'Unmodified captures · Files: round 08. Mail and Photos: round 07. Browser and Preview: round 06. Earlier rounds retain a floating Dock. Messages are fictional fixtures.', captureLabel: 'Capture round', captureSource: 'Source record',
    compareEyebrow: 'The difference is in the details', compareTitle: 'Same everyday.<br>A different feel.', compareIntro: 'Move the divider to compare stock Fedora Kinoite with Union.', compareLabel: 'Before and after screenshots', slider: 'Adjust the divider between stock Fedora and Union screenshots', drag: 'Drag to compare', before: 'Stock Fedora', after: 'Union', original: 'Open original', compareNote: 'Unmodified 1920 × 1200 captures at 100% scale. Union captures come from test VMs in rounds 06 / 07 / 08, recorded separately from ISO installation and online update checks. Layouts, sample content and interaction states differ. Only Files in this comparison shows the full-width panel.', compareDetails: ['Chinese and Latin filenames with the full-width panel, captured in round 08.', 'From a small information-panel image to a dedicated preview; the sample images differ.', 'A consistent browser frame; websites control their own content.', 'Three-pane reading, medium-weight emphasis and the round 07 floating Dock.', 'The same album, with a consistent sidebar, window frame and Dock.'],
    typeEyebrow: 'Thoughtful typography', typeTitle: 'Every character.<br><span>At home.</span>', typeIntro: 'Adwaita Sans meets Noto Chinese in the desktop interface. Regular text uses weight 400; theme-managed Chinese headings and emphasis use a true 500 Medium. Clearer hierarchy, from filenames to messages.', typeSample: '字里行间，<br>留一点从容。', typeEnglish: 'A little room to read.', typeMeta: 'Website specimen · 500 Medium', typeFamily: 'Noto Sans CJK', typeLink: 'See real Chinese typography', typeCaption: 'Union text preview · Simplified Chinese and Latin',
    dockEyebrow: 'A lighter desktop', dockTitle: 'Room for your day.<br>Everything in place.', dockText: 'A full-width translucent panel meets the bottom edge of the screen. Workspaces sit on the left, everyday apps in the center, and the tray and date on the right. Native launching, switching and running indicators stay within reach.', dockLink: 'See the latest panel capture',
    foundationEyebrow: 'Calm on the surface. Capable underneath.', foundationTitle: 'Familiar apps.<br>Solid foundations.', foundationIntro: 'Built on Fedora Kinoite. Focused on the everyday.<br>The Linux foundations you know are still here.', foundation: [
      ['Fedora Atomic', 'Built to move forward.', 'Retains Fedora’s Atomic deployments, update origin and system rollback entry.'],
      ['KDE Plasma', 'Familiar feels right.', 'Dolphin, Firefox, Thunderbird and Gwenview, brought together by considered visual details.'],
      ['Open development', 'See how it comes together.', 'Explore the source, original screenshots, installation guide and verification records in the public repository.'],
    ], source: 'Explore the source',
    downloadEyebrow: 'AVEN 0.4.0 · ONLINE INSTALL & UPDATES', downloadTitle: 'Make a little<br>room for Union.', downloadIntro: 'Already on Kinoite? Add Aven.<br>Get the next improvement through component updates.', download: 'Download Union 0.3.1 ISO', pendingDownload: 'ISO release in preparation', pendingNote: 'The single-file image and verification details will appear when publication is complete.', guide: 'Read the install guide', platform: 'x86_64 · Fedora Kinoite 44 · Offline installer ISO', prerelease: 'An experimental Plasma 6.8 Beta prototype. Start in a virtual machine.', sizeLabel: 'File size', checksumLabel: 'SHA-256 checksum', manifestLabel: 'Download metadata JSON', installTitle: 'Install using the ISO', installSteps: ['Download the complete Aven Union 0.3.1 ISO file. No multipart assembly is needed.', 'Check the file size and compare its SHA-256 with the checksum on this page.', 'Attach the ISO to a virtual machine, or write it to a USB drive of at least 16 GB. Follow the installation guide.'], installNote: 'This is an installer, not a live desktop. See the guide for installation steps and the verified scope.',
    evidenceTitle: 'About the screenshots and release', evidenceText: 'Original screenshot pixels are preserved without retouching. The hero and Files show the round 08 panel; Mail and Photos are round 07; Browser, Preview and typography are round 06. The online update section includes a separate Chinese installation capture. Screenshot rounds, ISO installation and online update checks are recorded separately. Albums, webpages and mail are test fixtures.', limits: 'Union’s overall and Chinese visual scores and three-second review remain pending. Online installation, component upgrades, interrupted-apply recovery and Aven profile rollback have been verified. This does not revalidate Fedora deployment rollback. See the ISO records for hardware and Secure Boot scope.', evidence: 'Installation verification', critic: 'Screenshots and comparisons', credits: 'Image sources and licenses', copyright: 'The Aven project', footerLine: 'Consider the everyday.', footerSource: 'Source code', releaseNotes: 'Release notes', languageLabel: 'Website language', dialogClose: 'Close screenshot', zoomHint: 'An unmodified capture. Open the original to inspect text at native resolution.',
  },
};
