#!/usr/bin/env python3
"""Generate original native KDE assets from Aven's focused token set.

No runtime dependency or style engine fork. Run from any working directory.
The optional Aurorae decoration must be checked in a real Plasma session before
being selected by the integrator. Its assets are not screenshot evidence.
"""
from __future__ import annotations

import json
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent
TOKENS = json.loads((ROOT / "tokens.json").read_text())


def put(path: str, content: str) -> None:
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content.rstrip() + "\n")


def rgb(hex_color: str) -> str:
    return ",".join(str(int(hex_color[i:i + 2], 16)) for i in (1, 3, 5))


def colors() -> None:
    s, f, a = (TOKENS[k] for k in ("surface", "foreground", "accent"))
    groups = {
        "Button": (s["raised"], s["hover"], f["primary"], f["secondary"]),
        "Complementary": (s["complementary"], "#2E4940", "#F6F7F2", "#BCC9BF"),
        "Header": (s["chrome"], s["hover"], f["primary"], f["secondary"]),
        "Header][Inactive": (s["chromeInactive"], s["chrome"], f["secondary"], f["secondary"]),
        "Selection": (s["selection"], a["hover"], f["selected"], "#E9F0E9"),
        "Tooltip": (s["raised"], s["alternate"], f["primary"], f["secondary"]),
        "View": (s["content"], s["alternate"], f["primary"], f["secondary"]),
        "Window": (s["chrome"], s["alternate"], f["primary"], f["secondary"]),
    }
    lines = ["# Generated by visual/generate_assets.py from visual/tokens.json.",
             "[ColorEffects:Disabled]", "Color=101,112,106", "ColorAmount=0", "ColorEffect=0",
             "ContrastAmount=0.55", "ContrastEffect=1", "IntensityAmount=0", "IntensityEffect=0", "",
             "[ColorEffects:Inactive]", "ChangeSelectionColor=true", "Color=220,232,224",
             "ColorAmount=0.1", "ColorEffect=2", "ContrastAmount=0.1", "ContrastEffect=2",
             "Enable=false", "IntensityAmount=0", "IntensityEffect=0", ""]
    for name, (bg, alt, fg, dim) in groups.items():
        selected = name in {"Selection", "Complementary"}
        entries = {"BackgroundNormal": bg, "BackgroundAlternate": alt,
                   "DecorationFocus": a["primary"], "DecorationHover": a["hover"],
                   "ForegroundNormal": fg, "ForegroundInactive": dim,
                   "ForegroundActive": fg if selected else a["primary"],
                   "ForegroundLink": "#C7E8DF" if selected else a["pressed"],
                   "ForegroundVisited": "#E2D1EA" if selected else "#775681",
                   "ForegroundNegative": "#FFD6CB" if selected else f["negative"],
                   "ForegroundNeutral": "#F3DFB1" if selected else f["neutral"],
                   "ForegroundPositive": "#C4E8CA" if selected else f["positive"]}
        lines.append(f"[Colors:{name}]")
        lines.extend(f"{key}={rgb(value)}" for key, value in entries.items())
        lines.append("")
    lines += ["[General]", "ColorScheme=AvenMist", "Name=Aven Mist", "Name[zh_CN]=Aven 薄雾",
              "Name[zh_TW]=Aven 薄霧", "shadeSortColumn=false", "", "[KDE]", "contrast=2", "", "[WM]"]
    for key, value in {"activeBackground": s["chrome"], "activeBlend": s["chrome"],
                       "activeForeground": f["primary"], "inactiveBackground": s["chromeInactive"],
                       "inactiveBlend": s["chromeInactive"], "inactiveForeground": f["secondary"]}.items():
        lines.append(f"{key}={rgb(value)}")
    put("color-schemes/AvenMist.colors", "\n".join(lines))


def icons() -> None:
    put("icons/Aven/index.theme", """[Icon Theme]
Name=Aven
Comment=Focused Aven folder icons; all remaining icons inherit Breeze.
Inherits=breeze,hicolor
Directories=scalable/places,scalable/apps,scalable/mimetypes

[scalable/places]
Size=64
MinSize=16
MaxSize=256
Context=Places
Type=Scalable

[scalable/apps]
Size=64
MinSize=16
MaxSize=256
Context=Applications
Type=Scalable

[scalable/mimetypes]
Size=64
MinSize=16
MaxSize=256
Context=MimeTypes
Type=Scalable
""")
    put("icons/Aven/scalable/apps/aven.svg", '''<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
  <title>Aven</title>
  <rect x="5" y="5" width="54" height="54" rx="15" fill="#326B60"/>
  <path d="M18 45 30.2 19.9Q32 16.2 33.8 19.9L46 45M23 35h18" fill="none" stroke="#F4F5EA" stroke-width="4.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>''')
    glyphs = {
        "folder": "",
        "folder-documents": '<path d="M25 24h10l5 5v15H25zM35 24v6h5M29 35h7M29 39h7"/>',
        "folder-download": '<path d="M32 24v14m-6-6 6 6 6-6M24 41v4h16v-4"/>',
        "folder-pictures": '<rect x="22" y="26" width="21" height="18" rx="2"/><path d="m23 41 6-6 5 5 4-4 4 5"/><circle cx="36.5" cy="31.5" r="1.5"/>',
        "user-home": '<path d="m22 34 10-9 10 9M25 32v13h14V32M30 45v-8h4v8"/>',
    }
    for name, glyph in glyphs.items():
        svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
  <title>{escape(name)} — Aven</title>
  <path d="M8 14a5 5 0 0 1 5-5h12l6 6h20a5 5 0 0 1 5 5v29a5 5 0 0 1-5 5H13a5 5 0 0 1-5-5Z" fill="#72988A"/>
  <path d="M8 21h48v28a5 5 0 0 1-5 5H13a5 5 0 0 1-5-5Z" fill="#BAD0BD"/>
  <path d="M8.5 21.5h47v27.5a4.5 4.5 0 0 1-4.5 4.5H13a4.5 4.5 0 0 1-4.5-4.5Z" fill="none" stroke="#537B6A" stroke-opacity=".24"/>
  <path d="M9 21.5h46" stroke="#E6EEE3" stroke-opacity=".75"/>
  <g fill="none" stroke="#416451" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">{glyph}</g>
</svg>'''
        put(f"icons/Aven/scalable/places/{name}.svg", svg)
    # Match KDE's common plural name without filesystem symlinks.
    put("icons/Aven/scalable/places/folder-downloads.svg",
        (ROOT / "icons/Aven/scalable/places/folder-download.svg").read_text())
    # Generic directory rows request the MIME icon, while named XDG folders
    # request places icons. Cover both, otherwise small generic folders inherit
    # Breeze's outlined inode-directory beside Aven's filled semantic folders.
    folder = (ROOT / "icons/Aven/scalable/places/folder.svg").read_text()
    put("icons/Aven/scalable/mimetypes/inode-directory.svg", folder)
    put("icons/Aven/scalable/places/folder-open.svg", folder)


def decoration() -> None:
    base = "aurorae/Aven"
    put(f"{base}/metadata.desktop", """[Desktop Entry]
Name=Aven
Comment=A quiet original window frame for Aven.
X-KDE-PluginInfo-Name=Aven
X-KDE-PluginInfo-Author=Aven
X-KDE-PluginInfo-Version=0.1
X-KDE-PluginInfo-License=MIT
""")
    put(f"{base}/Avenrc", f"""[General]
TitleAlignment=Left
TitleVerticalAlignment=Center
Animation=100
ActiveTextColor={rgb(TOKENS['foreground']['primary'])},255
InactiveTextColor={rgb(TOKENS['foreground']['secondary'])},255
UseTextShadow=false
HaloActive=false
HaloInactive=false
LeftButtons=
RightButtons=IAX
Shadow=true
DecorationPosition=0

[Layout]
BorderLeft=1
BorderRight=1
BorderBottom=1
TitleEdgeTop=5
TitleEdgeBottom=5
TitleEdgeLeft=16
TitleEdgeRight=8
TitleEdgeTopMaximized=0
TitleEdgeBottomMaximized=0
TitleEdgeLeftMaximized=16
TitleEdgeRightMaximized=0
TitleBorderLeft=0
TitleBorderRight=12
TitleHeight=28
ButtonWidth=28
ButtonHeight=28
ButtonSpacing=4
ButtonMarginTop=0
ExplicitButtonSpacer=12
PaddingTop=24
PaddingBottom=24
PaddingLeft=24
PaddingRight=24
""")
    # A 160px reference frame: 24px shadow, 10px corner, 92px stretch center.
    # Each element has explicit transparent bounds: predictable FrameSvg slicing.
    fragments = []
    geometry = {
        "topleft": (0, 0, 34, 34), "top": (34, 0, 92, 34), "topright": (126, 0, 34, 34),
        "left": (0, 34, 34, 92), "center": (34, 34, 92, 92), "right": (126, 34, 34, 92),
        "bottomleft": (0, 126, 34, 34), "bottom": (34, 126, 92, 34), "bottomright": (126, 126, 34, 34),
    }
    def slice_shape(part: str, spread: float, fill: str, opacity: float = 1) -> str:
        low, high, radius = 24 - spread, 136 + spread, 10 + spread
        attrs = f'fill="{fill}" opacity="{opacity:.5f}"'
        if part == "center":
            return f'<rect x="34" y="34" width="92" height="92" {attrs}/>'
        if part in {"top", "bottom"}:
            y = low if part == "top" else 126
            return f'<rect x="34" y="{y}" width="92" height="{radius}" {attrs}/>'
        if part in {"left", "right"}:
            x = low if part == "left" else 126
            return f'<rect x="{x}" y="34" width="{radius}" height="92" {attrs}/>'
        paths = {
            "topleft": f'M34 {low}A{radius} {radius} 0 0 0 {low} 34H34Z',
            "topright": f'M126 {low}A{radius} {radius} 0 0 1 {high} 34H126Z',
            "bottomleft": f'M{low} 126A{radius} {radius} 0 0 0 34 {high}V126Z',
            "bottomright": f'M{high} 126A{radius} {radius} 0 0 1 126 {high}V126Z',
        }
        return f'<path d="{paths[part]}" {attrs}/>'

    for state, fill, opacity in [("decoration", TOKENS["surface"]["chrome"], 0.16),
                                  ("decoration-inactive", TOKENS["surface"]["chromeInactive"], 0.08),
                                  ("mask", "#FFFFFF", 0.0)]:
        offset = 0 if state == "decoration" else (180 if state == "decoration-inactive" else 360)
        for part, (x, y, w, h) in geometry.items():
            shadows = []
            # Vector-only Gaussian-like shadow: SVG filters are not required by Qt.
            if opacity:
                for spread in range(22, 0, -1):
                    alpha = opacity * (1 - spread / 24) ** 2 / 10
                    shadows.append(slice_shape(part, spread, "#18312A", alpha))
            # Do not stroke slice edges. QtSvg includes the stroke's endpoint
            # envelope in boundsOnElement even with the default butt caps:
            # a 92px edge became 93px and a 34px corner became 34.5px. KSvg then
            # stretched those mismatched bounds against an exact-sized mask,
            # producing the witnessed corner crosses. Two contained fills form
            # the 1px boundary without extending any nine-slice bounding box.
            border = '' if state == 'mask' or part == 'center' else (
                slice_shape(part, 0, "#637568", 0.22) + slice_shape(part, -1, fill)
            )
            fragments.append(f'<g id="{state}-{part}" transform="translate({offset} 0)"><rect x="{x}" y="{y}" width="{w}" height="{h}" fill="#000" opacity="0"/>{"".join(shadows)}{slice_shape(part, 0, fill)}{border}</g>')
        if state != "mask":
            fragments.append(f'<rect id="{state.replace("decoration", "decoration-maximized")}-center" x="{offset+34}" y="180" width="92" height="92" fill="{fill}"/>')
    # Stretch straight edge slices; tiling their antialiased stroke bounds
    # produces a visible seam every 92px in the actual KWin decoration.
    put(f"{base}/decoration.svg", '<svg xmlns="http://www.w3.org/2000/svg" width="520" height="280" viewBox="0 0 520 280"><rect id="hint-stretch-borders" x="0" y="270" width="1" height="1"/>' + ''.join(fragments) + '</svg>')
    glyphs = {
        "close": '<path d="m9 9 10 10M19 9 9 19"/>',
        "minimize": '<path d="M9 16h10"/>',
        "maximize": '<rect x="9" y="9" width="10" height="10" rx="1"/>',
        "restore": '<path d="M11 9V7h10v10h-2"/><rect x="7" y="11" width="10" height="10" rx="1"/>',
        "keepabove": '<path d="m9 16 5-5 5 5M9 8h10"/>',
        "keepbelow": '<path d="m9 12 5 5 5-5M9 20h10"/>',
        "shade": '<path d="m9 17 5-5 5 5M8 8h12"/>',
        "alldesktops": '<circle cx="14" cy="14" r="6"/><path d="M14 8v12M8 14h12"/>',
        "help": '<path d="M11 10a3 3 0 0 1 6 0c0 2-3 2-3 5M14 19v.01"/>',
        "appmenu": '<path d="M8 10h12M8 14h12M8 18h12"/>',
    }
    for name, glyph in glyphs.items():
        parts = []
        for i, state in enumerate(("active", "inactive", "hover", "hover-inactive", "pressed", "pressed-inactive", "deactivated", "deactivated-inactive")):
            background = "#E5ECE6" if "hover" in state else "#D7E2D9" if "pressed" in state else "none"
            color = "#65706A" if state in ("inactive", "deactivated", "deactivated-inactive") else "#34473D"
            if name == "close" and ("hover" in state or "pressed" in state):
                background, color = "#F0DCD6", "#923F36"
            opacity = ".4" if "deactivated" in state else "1"
            parts.append(f'<g id="{state}-center" transform="translate({i*32} 0)" opacity="{opacity}"><rect width="28" height="28" fill="#000" opacity="0"/><rect x="1" y="1" width="26" height="26" rx="6" fill="{background}"/><g fill="none" stroke="{color}" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">{glyph}</g></g>')
        put(f"{base}/{name}.svg", '<svg xmlns="http://www.w3.org/2000/svg" width="256" height="28" viewBox="0 0 256 28">' + ''.join(parts) + '</svg>')


if __name__ == "__main__":
    colors()
    icons()
    decoration()
    print("Generated Aven color scheme, focused folder icons and optional Aurorae decoration.")
